name: Dev CI

on:
  push:
    branches: [dev]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 1.5

    steps:
      - name: check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Install dependencies
        run: npm run ci-setup

      - name: Format using Prettier and ESLint
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: Dev CI - Apply formatting changes
          branch: dev