name: Dev CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1.5

    steps:
      - name: check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Install dependencies
        run: npm run ci-setup

      - name: Format using Prettier
        run: npm run format

      - name: Run ESLint
        run: npm run lint