name: Main CI

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 1.5

    steps:
      - name: check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Install dependencies
        run: npm run ci-setup

      - name: Format using Prettier and ESLint
        run: npm run format
